
  - uses: actions/checkout@v4

  - name: Install system dependencies
    run: |
      sudo apt-get update
      sudo apt-get install -y libcurl4-openssl-dev

  - uses: r-lib/actions/setup-r@v2

  - uses: r-lib/actions/setup-renv@v2

  - uses: quarto-dev/quarto-actions/render@v2
    with:
      to: html

  - uses: quarto-dev/quarto-actions/publish@v2
    with:
      target: gh-pages
